# Generated by Django 5.1.2 on 2025-04-03 03:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('blocation', models.CharField(max_length=255, verbose_name='Branch Location')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 't_branch',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255, unique=True, verbose_name='Role Name')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 't_role',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
                ('cdescription', models.TextField(blank=True, null=True, verbose_name='Category Description')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'db_table': 't_service_category',
                'ordering': ['cname'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('cemail', models.EmailField(max_length=254, unique=True, verbose_name='Customer Email')),
                ('cphone', models.CharField(max_length=15, verbose_name='Customer Phone')),
                ('cimage', models.ImageField(blank=True, null=True, upload_to='customers/', verbose_name='Customer Image')),
                ('token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 't_customer',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=255, verbose_name='Service Name')),
                ('sprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Service Price')),
                ('sduration', models.CharField(max_length=255, unique=True, verbose_name='Duration')),
                ('simage', models.ImageField(blank=True, null=True, upload_to='media/media/meia/images/', verbose_name='Service Image')),
                ('scomment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='App.servicecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 't_service',
                'ordering': ['sname'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('wfirst', models.CharField(max_length=255, verbose_name='Worker First Name')),
                ('wname', models.CharField(max_length=255, verbose_name='Worker Last Name')),
                ('wphone', models.CharField(max_length=15, unique=True, verbose_name='Worker Phone')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='App.branch', verbose_name='Branch')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='App.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
                'db_table': 't_worker',
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Event Description')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Time')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='App.branch', verbose_name='Branch')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='App.service', verbose_name='Service')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='App.worker', verbose_name='Worker')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'db_table': 't_calendar_event',
                'ordering': ['start_time'],
            },
        ),
    ]
