# Generated by Django 5.1.2 on 2025-04-15 07:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('blocation', models.CharField(max_length=255, verbose_name='Branch Location')),
                ('bimage', models.ImageField(blank=True, null=True, upload_to='media/images', verbose_name='Branch Image')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 't_branch',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255, unique=True, verbose_name='Role Name')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 't_role',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
                ('cdescription', models.TextField(blank=True, null=True, verbose_name='Category Description')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'db_table': 't_service_category',
                'ordering': ['cname'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=255, verbose_name='Service Name')),
                ('sprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Service Price')),
                ('sduration', models.CharField(max_length=255, unique=True, verbose_name='Duration')),
                ('simage', models.ImageField(blank=True, null=True, upload_to='media/media/meia/images/', verbose_name='Service Image')),
                ('scomment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='App.servicecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 't_service',
                'ordering': ['sname'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('wfirst', models.CharField(max_length=255, verbose_name='Worker First Name')),
                ('wname', models.CharField(max_length=255, verbose_name='Worker Last Name')),
                ('wphone', models.CharField(max_length=15, unique=True, verbose_name='Worker Phone')),
                ('worker_image', models.ImageField(blank=True, null=True, upload_to='worker_images/', verbose_name='Worker Image')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='App.branch', verbose_name='Branch')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='App.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
                'db_table': 't_worker',
            },
        ),
        migrations.CreateModel(
            name='Made',
            fields=[
                ('made_id', models.AutoField(primary_key=True, serialize=False)),
                ('made_image', models.ImageField(upload_to='made_images/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('made_service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.servicecategory')),
                ('made_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.worker')),
            ],
            options={
                'verbose_name': 'Made Work',
                'verbose_name_plural': 'Made Works',
                'db_table': 't_made',
                'ordering': ['made_id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=255)),
                ('cemail', models.EmailField(max_length=254, unique=True)),
                ('cphone', models.CharField(max_length=15)),
                ('cimage', models.ImageField(blank=True, null=True, upload_to='customer_images/')),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('blacklist', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 't_customer',
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Event Description')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Time')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='App.branch', verbose_name='Branch')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='App.service', verbose_name='Service')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='App.worker', verbose_name='Worker')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'db_table': 't_calendar_event',
                'ordering': ['start_time'],
            },
        ),
    ]
