# Generated by Django 5.1.2 on 2025-04-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='simage',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/', verbose_name='Service Image'),
        ),
    ]
