# Generated by Django 5.1.2 on 2025-04-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/images', verbose_name='Branch Image'),
        ),
    ]
